name: Build and Deploy
on:
  push:
    branches:
      - test
  release:
    types:
      - published

env:
  VERSIONS_PATH: /

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Versions Path
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo VERSIONS_PATH=/versions/$GITHUB_REF_NAME/ >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          cd docs
          npm install
          npm run build
      - name: vuepress-deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          TARGET_FOLDER: ${{ env.VERSIONS_PATH }}
          CLEAN: true
          CLEAN_EXCLUDE: '["versions"]'