name: Build and Deploy
on:
  push:
    branches:
      - test
  release:
    types:
      - published

env:
  notifyBCDocVersion_PATH: /

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update notifyBCDocVersion_PATH
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo notifyBCDocVersion_PATH=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2)/ >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          cd docs
          yarn install
          yarn build
      - name: vuepress-deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          TARGET_FOLDER: ${{ env.notifyBCDocVersion_PATH }}
          CLEAN: true
          CLEAN_EXCLUDE: '["version"]'